### PR TITLE
Do nothing if valid push certificate is already attached

### PR DESCRIPTION
**Pull request by aafa**
Do nothing If valid certificate that expires no less than in 2 weeks was found.
I'm pretty new with ruby so I might have missed something here.  Any critics are welcome.

Related issue #20

### CODE REVIEW

**Comment by aafa** [comment]
Looks like something's wrong. My bad?

**Comment by KrauseFx** [comment]
Sorry, that's my fault, I'll check it out, thanks for submitting a pull request.

**Comment by KrauseFx** [comment]
This in combination with https://github.com/KrauseFx/fastlane/pull/200 solving https://github.com/KrauseFx/PEM/issues/20

You are **the best** :+1:

**Comment by KrauseFx** [comment]
This looks awesome! :+1: also, thank you for providing tests!

**Comment by KrauseFx** [comment]
I just added the `--force` option: https://github.com/KrauseFx/PEM/commit/47ce1ec9a6b1fcfec494cc3f9019f1a826846b28 and updated the README: https://github.com/KrauseFx/PEM/commit/66c38d6ee8103cf761725dcee81837144c038230 :+1:

**Comment by aafa** [comment]
Great! :+1:

**Pull request merged**
